askcompany/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from django.views.generic import TemplateView
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('', RedirectView.as_view(pattern_name='shop:item_list'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.urls import path

app_name = 'blog'

urlpatterns = [
]

shop/urls.py
from django.urls import path, re_path, register_converter
from .converters import FourDigitYearConverter
from . import views

register_converter(FourDigitYearConverter, 'yyyy')

app_name = 'shop'

urlpatterns = [
    path('archives/<yyyy:year>/', views.archives_year, name='archives_year'),
    path('', views.item_list, name='item_list'),
    path('<int:pk>/', views.item_detail, name='item_detail'),
    path('<int:pk>/edit/', views.item_edit, name='item_edit'),
    path('new/', views.item_new, name='item_new'),
]

blog/models.py
from django.db import models
from askcompany.utils import uuid_upload_to


class Post(models.Model):
    author_name = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    gwaesa = models.TextField()    
    danwal = models.TextField()
    sangwal = models.TextField()    
    mununwal = models.TextField()  
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

common/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse
from askcompany.utils import uuid_upload_to


class Item(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    is_publish = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # return '<{}> {}'.format(self.pk, self.name)
        return f'<{self.pk}> {self.name}'

    def get_absolute_url(self):
        # return reverse('shop:item_detail', args=[self.pk])
        return reverse('shop:item_detail', kwargs={'pk': self.pk})

shop/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
    

common/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
import logging
import re
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, UpdateView
from .models import Item
from .forms import ItemForm

logger = logging.getLogger(__name__)  # __name__ => "shop.views"


def archives_year(request, year):
    return HttpResponse('{}년도에 대한 기록'.format(year))


def item_list(request):
    qs = Item.objects.all()

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(name__icontains=q)

    logger.debug('query : {}'.format(q))

    return render(request, 'shop/item_list.html', {
        'item_list': qs,
        'q': q,
    })


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html', {
        'item': item,
    })



# def item_new(request, item=None):
#     if request.method == 'POST':
#         form = ItemForm(request.POST, request.FILES, instance=item)
#         if form.is_valid():
#             item = form.save()  # ModelForm에서 제공
#             return redirect(item)
#     else:
#         form = ItemForm(instance=item)

#     return render(request, 'shop/item_form.html', {
#         'form': form,
#     })


# def item_edit(request, pk):
#     item = get_object_or_404(Item, pk=pk)
#     return item_new(request, item)


item_new = CreateView.as_view(model=Item, form_class=ItemForm)

item_edit = UpdateView.as_view(model=Item, form_class=ItemForm)

askcompany/templates/layout.html
{% load static fresh_static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
        <title>{% block title %}Ask Company{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
        {% block extra_head %}
            <link rel="stylesheet" href="{% fresh_static "main.css" %}" />
        {% endblock %}
    </head>
    <body>

        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
            <h5 class="my-0 mr-md-auto font-weight-normal">
                Ask Company
            </h5>
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="#">Features</a>
                <a class="p-2 text-dark" href="#">Enterprise</a>
                <a class="p-2 text-dark" href="#">Support</a>
                <a class="p-2 text-dark" href="#">Pricing</a>
            </nav>
            <a class="btn btn-outline-primary" href="#">Sign up</a>
        </div>

        <div class="container">
            <div class="col-sm-12">
                {% block content %}
                {% endblock %}
            </div>

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
                        <small class="d-block mb-3 text-muted">© 2017-2018. Ask Company.</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Features</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Cool stuff</a></li>
                            <li><a class="text-muted" href="#">Random feature</a></li>
                            <li><a class="text-muted" href="#">Team feature</a></li>
                            <li><a class="text-muted" href="#">Stuff for developers</a></li>
                            <li><a class="text-muted" href="#">Another one</a></li>
                            <li><a class="text-muted" href="#">Last time</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Resources</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Resource</a></li>
                            <li><a class="text-muted" href="#">Resource name</a></li>
                            <li><a class="text-muted" href="#">Another resource</a></li>
                            <li><a class="text-muted" href="#">Final resource</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>About</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Team</a></li>
                            <li><a class="text-muted" href="#">Locations</a></li>
                            <li><a class="text-muted" href="#">Privacy</a></li>
                            <li><a class="text-muted" href="#">Terms</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

        {% block extra_body %}
            <script src="{% static "main.js" %}"></script>
        {% endblock %}
    </body>
</html>

askcompany/templates/root.html
{% extends "layout.html" %}

{% block content %}
    첫 페이지
{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load fresh_static %}

{% block title %}Blog by Ask Company{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% fresh_static "blog/blog.css" %}" />
{% endblock %}

{% block extra_body %}
    {{ block.super }}
{% endblock %}

shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}
{% load humanize %}

{% block content %}

    <div class="card">
        <div class="card-header">
            {{ item.name }}
            &dash; {{ item.price|intcomma }}원
        </div>
        <div class="card-body">
            {% if item.photo %}
                <img src="{{ item.photo.url }}" style="max-width: 100%;" />
            {% endif %}
      
            {% if item.desc %}
                <p>
                    {{ item.desc|linebreaks }}
                </p>
            {% endif %}
        </div>
        <div class="card-footer">
            <a href="{% url "shop:item_list" %}" class="btn btn-primary">목록</a>
            <a href="{% url "shop:item_edit" item.pk %}" class="btn btn-secondary">수정</a>
        </div>
    </div>
{% endblock %}

shop/templates/shop/item_form.html
{% extends "shop/layout.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            New Item
        </div>
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <table class="table table-bordered">
                    {{ form.as_table }}
                </table>
                <input type="submit" value="저장하기" class="btn btn-primary" />
                <a href="{% url "shop:item_list" %}" class="btn btn-secondary">목록으로</a>
            </form>
        </div>
    </div>
{% endblock %}

shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}

{% block content %}

    <div class="mb-3">
        <form action="" method="GET">
            <input type="text" name="q" value="{{ q }}" class="form-control" placeholder="검색어를 입력해주세요." />
        </form>
    </div>

    <table class="table table-hover table-bordered">
        <tbody>
            {% for item in item_list %}
                <tr>
                    <td>
                        <a href="{{ item.get_absolute_url }}">
                            {{ item.name }}
                        </a>
                    </td>
                    <td>{{ item.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url "shop:item_new" %}" class="btn btn-primary">
        New Item
    </a>
{% endblock %}

shop/templates/shop/item_list.jinja
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Blog for Ask Company</title>
    </head>
    <body>
        <h1>Ask Company</h1>

        {{ user }}

        <form action="" method="GET">
            <input type="text" name="q" value="{{ q }}" />
            <input type="submit" value="search" />
        </form>

        <ul>
            {% for item in item_list %}
                <li>
                    {{ item.name }}
                    {{ item.price }}
                    {{ item.desc }}
                </li>
            {% endfor %}
        </ul>
    </body>
</html>

shop/templates/shop/layout.html
{% extends "layout.html" %}
{% load fresh_static %}

{% block title %}Shop by Ask Company{% endblock %}

{% block extra_body %}
    {{ block.super }}
{% endblock %}